package com;
// Generated Feb 26, 2021, 12:48:43 PM by Hibernate Tools 4.0.1.Final

/**
 * Emp generated by hbm2java
 */
public class Emp implements java.io.Serializable {

	private Integer eid;
	private Depart depart;
	private String ename;
	private String salary;

	public Emp() {
	}

	public Emp(Depart depart, String ename, String salary) {
		this.depart = depart;
		this.ename = ename;
		this.salary = salary;
	}

	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	public Depart getDepart() {
		return this.depart;
	}

	public void setDepart(Depart depart) {
		this.depart = depart;
	}

	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public String getSalary() {
		return this.salary;
	}

	public void setSalary(String salary) {
		this.salary = salary;
	}

}
