package com.pojo;

// Generated 8 Oct, 2020 11:38:01 AM by Hibernate Tools 3.4.0.CR1

/**
 * Emp generated by hbm2java
 */
public class Emp implements java.io.Serializable {

	private Integer eid;
	private Depart depart;
	private String ename;
	private String sal;

	public Emp() {
	}

	public Emp(Depart depart, String ename, String sal) {
		this.depart = depart;
		this.ename = ename;
		this.sal = sal;
	}

	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	public Depart getDepart() {
		return this.depart;
	}

	public void setDepart(Depart depart) {
		this.depart = depart;
	}

	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public String getSal() {
		return this.sal;
	}

	public void setSal(String sal) {
		this.sal = sal;
	}

}
